services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      FRONTEND_URL: http://localhost:5173
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./Frontend:/usr/src/app         
      - /usr/src/app/node_modules       
    environment:
      NODE_ENV: development
      VITE_API_BASE_URL: http://backend:3000
    ports:
      - "5173:5173"
    depends_on:
      - backend
